### PR TITLE
chore: update module checks workflow

### PR DESCRIPTION
**Pull request by malachi-constant**
## Describe your changes
- updated `get-modules` workflow to only run tests against changed files in `modules/**`
- adds workflow specific to changes for `requirements-dev.txt` so all static checks are run

## Checklist before requesting a review

- [X] I updated `CHANGELOG.MD` with a description of my changes
- [X] If the change was to a module, I ran the code validation script (`scripts/validate.sh`)
- [X] If the change was to a module, I have added thorough tests
- [X] If the change was to a module, I have added/updated the module's README.md
- [X] If a module was added, I added a reference to the module to the repository's README.md
- [X] I verified that my code deploys successfully using `seedfarmer apply`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: AIOpsModuleTestsInfrastruct-doMLXEYsnmxr
* Commit ID: e511460bf6db6a50943d0a0784ec9fae49f42291
* Result: SUCCEEDED
* [Build Logs](https://ythfngxmh6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=8fd50e6d-8e75-46c4-803f-0275681e29cb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: AIOpsModuleTestsInfrastruct-doMLXEYsnmxr
* Commit ID: 44c3bc19bb351ec56d6569cf6c82b1a40e611437
* Result: SUCCEEDED
* [Build Logs](https://ythfngxmh6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=15671f95-16aa-485a-9fe8-b04075a7cfd2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: AIOpsModuleTestsInfrastruct-doMLXEYsnmxr
* Commit ID: dc8ccc537302c726236a7b7bccfecdce61e2cae8
* Result: SUCCEEDED
* [Build Logs](https://ythfngxmh6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fe9515f7-ea33-4f75-9048-c0197594a378%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: AIOpsModuleTestsInfrastruct-doMLXEYsnmxr
* Commit ID: 8dc3005b29e5d25ce00b925677e7dccbed6ef73d
* Result: SUCCEEDED
* [Build Logs](https://ythfngxmh6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4b493ae9-6fe0-4941-a970-d446f0a54a92%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Review by LeonLuttenberger — COMMENTED** [review]
If `requirements-dev.txt` changes, I think we should run the workflow on all modules. For example, if we update `ruff` or `mypy`, I think we want to make sure all the modules are well formatter.

Other than that, great job! I think it's a good change

**Comment by malachi-constant** [comment]
> If `requirements-dev.txt` changes, I think we should run the workflow on all modules. For example, if we update `ruff` or `mypy`, I think we want to make sure all the modules are well formatter.
> 
> Other than that, great job! I think it's a good change

Ahh yes good call @LeonLuttenberger will add some conditional stuff in there.

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: AIOpsModuleTestsInfrastruct-doMLXEYsnmxr
* Commit ID: 2c4e5fc2a6ed664fb256e4dbe958b9907330d240
* Result: SUCCEEDED
* [Build Logs](https://ythfngxmh6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b2e57673-8ea7-4846-b385-93f650bfbc87%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
> > If `requirements-dev.txt` changes, I think we should run the workflow on all modules. For example, if we update `ruff` or `mypy`, I think we want to make sure all the modules are well formatter.
> > Other than that, great job! I think it's a good change
> 
> Ahh yes good call @LeonLuttenberger will add some conditional stuff in there.

@LeonLuttenberger cleanest way I could see was just to have another similar workflow only targeted to `requirements-dev.txt`

**Review by kukushking — APPROVED** [review]
Thank you, that's really helpful!

**Review by LeonLuttenberger — APPROVED** [review]

**Review by srinivasreddych — APPROVED** [review]

**Pull request merged**
